# Training configuration
GPU: [0]

VERBOSE: False

MODEL:
  MODE: 'mas3k'    

# Optimization arguments.
OPTIM: 
  BATCH:  2
  EPOCHS: 200 
  LR_INITIAL: 5e-5    
  LR_MIN: 1e-7      

TRAINING:
  VAL_AFTER_EVERY: 1
  VAL_IMAGE_SAVE:  100   
  RESUME: False  
  TRAIN_PS: 256  
  VAL_PS: 352   
  TRAIN_DIR: 'D:/marine_data/MAS3K_low_n/MAS3K/fold2/train' 
  VAL_DIR: 'D:/marine_data/MAS3K_low_n/MAS3K/fold2/valid_ori'    

  SAVE_DIR: './checkpoints'           
  IMAGE_SAVE_DIR: './checkpoints/save_images'

